### ISSUE TITLE
微信异步验签失败

### ISSUE THREAD

**Issue by liaohongxing** [go-pay/gopay#140]
利用您的库对接微信支付 ，但是签名验证不通过 
```go
func WechatNotify(w http.ResponseWriter, r *http.Request) (code int, body interface{}) {
	ApiV3Key := lgini.Use().Wechat.ApiV3Key
	PCContent := lgini.Use().Wechat.PCContent

	xlog.Debug(lgini.Use().Wechat)

	notifyReq, err := wechat.V3ParseNotify(r)
	if err != nil {
		xlog.Debug(err)
		return http.StatusInternalServerError, &wechat.V3NotifyRsp{Code: gopay.FAIL, Message: err.Error()}
	}

	xlog.Debug(notifyReq)

	xlog.Debug(notifyReq.SignInfo)

	if err := notifyReq.VerifySign(PCContent); err != nil {
		xlog.Debug(err)
		return http.StatusInternalServerError, &wechat.V3NotifyRsp{Code: gopay.FAIL, Message: err.Error()}
	}

        .....
}
```

报错内容如下 

```
2021/06/25 11:59:27.467055 common.go:170: [DEBUG] >> verify sign failed: crypto/rsa: verification error
```

希望您能帮忙看下，谢谢~

**Comment by iGoogle-ink** [comment]
你传的 PCContent  是微信平台公钥证书的内容（需要通过接口获取的），请确认是否正确，

**Comment by liaohongxing** [comment]
微信发给我一组证书，里面有一个私钥证书 ，公钥证书 ，还有个p12证书文件 ，这个PCContent是我直接读取的这个文件夹里面的公钥证书内容 ，请问下 直接填这个 公钥证书 可以吗

**Comment by iGoogle-ink** [comment]
> 微信发给我一组证书，里面有一个私钥证书 ，公钥证书 ，还有个p12证书文件 ，这个PCContent是我直接读取的这个文件夹里面的公钥证书内容 ，请问下 直接填这个 公钥证书 可以吗

异步通知验签，需要微信平台证书和证书序列号，通过 client.GetPlatformCerts() 获取的，如果有问题，请加微信加群垂询吧

**Comment by gozelus** [comment]
同样的问题
pkContent 使用的是微信接口返回的publickey的值

**Comment by sinhang** [comment]
> > 微信发给我一组证书，里面有一个私钥证书 ，公钥证书 ，还有个p12证书文件 ，这个PCContent是我直接读取的这个文件夹里面的公钥证书内容 ，请问下 直接填这个 公钥证书 可以吗
> 
> 异步通知验签，需要微信平台证书和证书序列号，通过 wechat.GetPlatformCerts() 获取的，如果有问题，请加微信加群垂询吧

两个证书居然不一致
PS：
生成的时候有一个
使用wechat获取的又是另外一个
那生成的时候那一个有什么用呢？
