### ISSUE TITLE
能否增加一下境外订单相关接口

### ISSUE THREAD

**Issue by on7line** [go-pay/gopay#141]
微信、阿里都有 

微信接口文档如下：
https://pay.weixin.qq.com/wiki/doc/api/external/declarecustom.php?chapter=18_1

万分感谢

**Comment by iGoogle-ink** [comment]
这几个接口是微信V2版本的，我看看。
那么，支付宝的呢？

**Comment by on7line** [comment]
大神v5,  支付宝地址：  https://opendocs.alipay.com/open/155/104778/

**Comment by iGoogle-ink** [comment]
好的

**Comment by iGoogle-ink** [comment]
> 大神v5, 支付宝地址： https://opendocs.alipay.com/open/155/104778/

兄弟，支付宝的这个有点搞不定啊，返回参数实在是搞不明白啊

**Comment by on7line** [comment]
好，牵扯报关的接口不好对接，辛苦啦

**Comment by iGoogle-ink** [comment]
v1.5.49，已经增加了相关接口，我没条件测试，你自己到时候测试下吧，这种接口使用率太低了

**Comment by on7line** [comment]
好的，谢谢

**Comment by on7line** [comment]
微信测试好用，感谢！
