### ISSUE TITLE
请问支付宝小程序获取会员手机号的签名的验证用哪个函数？

### ISSUE THREAD

**Issue by DehaiWang** [go-pay/gopay#161]
这个是支付宝小程序的内容加密的链接
https://opendocs.alipay.com/mini/api/dwou7f
https://opendocs.alipay.com/mini/2019110100244259

返回的数据里边有：
 response       报文（密文）
 sign   对 response 报文的签名

目前用 alipay.DecryptOpenDataToBodyMap(response, aesKey ) 解密报文正常，能拿到用户的手机号码，
用哪个函数进行验证签名呢？
谢谢。

**Comment by iGoogle-ink** [comment]
![image](https://user-images.githubusercontent.com/17245594/127681045-c30a1703-6bc2-48ad-963a-4b706b9c9285.png)
我认为是这个验签，`公钥证书异步通知验签 ` 
可以参考一下试试行不行
![image](https://user-images.githubusercontent.com/17245594/127681381-8990b8c0-84a5-4366-a106-3d9f5dc3e8c0.png)
