### ISSUE TITLE
why deprecated functionSetPrivateKeyType() ?

### ISSUE THREAD

**Issue by shuntan** [go-pay/gopay#177]

**Comment by iGoogle-ink** [comment]
@shuntan 
你可以看看方法实现，忽略了PKCS1 和PKCS8 的类型，不管你传哪个类型，只要最终能成功即可

![image](https://user-images.githubusercontent.com/17245594/130622990-7ecf0913-0a99-410e-af50-da6bfc92f5f8.png)
![image](https://user-images.githubusercontent.com/17245594/130622925-ddb03f50-4f0a-4f9b-aab7-fdd89799e0b9.png)
