### ISSUE TITLE
希望支持apple支付

### ISSUE THREAD

**Issue by codingcn** [go-pay/gopay#198]
需要上架IOS的应用，涉及到虚拟支付，就必须接入apple pay。所以这是种非常重要的支付方式

**Comment by iGoogle-ink** [comment]
@codingcn 
苹果支付，应该是 苹果APP 开发处理的，第三方无法涉及，Apple Pay 里已经有个服务端的校验接口，你可以先研究一下 苹果支付流程

**Comment by codingcn** [comment]
app支付服务端只需要验证这一个接口，比较简单

https://developer.apple.com/documentation/appstorereceipts/verifyreceipt
