### ISSUE TITLE
服务商模式特约商户进件报错平台证书序列号Wechatpay-Serial错误

### ISSUE THREAD

**Issue by joesonm** [go-pay/gopay#206]

**Comment by joesonm** [comment]
![image](https://user-images.githubusercontent.com/49093603/145683478-58268125-fe4d-4cde-bf16-6a7389ac44be.png)

**Comment by joesonm** [comment]
client, err := wechatSDKV3.NewClientV3(mchid, serialNo, apiKey, pkContent)
	if err != nil {
		return nil, err
	}
	err = client.AutoVerifySign()
	if err != nil {
		return nil, err
	}

**Comment by joesonm** [comment]
// NewClientV3 初始化微信客户端 V3
	//	mchid：商户ID
	// 	serialNo：商户证书的证书序列号
	//	apiV3Key：APIv3Key，商户平台获取
	//	privateKey：商户API证书下载后，私钥 apiclient_key.pem 读取后的字符串内容
	client, err = NewClientV3(MchId, SerialNo, APIv3Key, PrivateKeyContent)
	if err != nil {
		xlog.Error(err)
		return
	}
	// 启用自动同步返回验签，并定时更新微信平台API证书
	err = client.AutoVerifySign()
	if err != nil {
		xlog.Error(err)
		return
	}
	
	1.已经使用上述代码初始化微信客户端，且获取到最新的平台证书公钥、序列号
	2.进件申请参数中敏感信息，已调用 client.V3EncryptText() 进行加密
	3.调用client.V3Apply4SubSubmit申请进件，报错 {"code":"PARAM_ERROR","message":"平台证书序列号Wechatpay-Serial错误"}

**Comment by qfly888** [comment]
解决了吗？我调用分账接口 `V3ProfitShareOrder` 出现了同样的错误

**Comment by joesonm** [comment]
> 解决了吗？我调用分账接口 `V3ProfitShareOrder` 出现了同样的错误

没有

**Comment by iGoogle-ink** [comment]
@qfly888 @joesonm 
我也会再看看这块业务流程，是不是真传错了 平台证书号

**Comment by iGoogle-ink** [comment]
麻烦两位替换成下面mod版本，试一下是否已经解决这个问题呢？
@qfly888 @joesonm 

```
github.com/go-pay/gopay v1.5.66-0.20211213054231-707b1683bc67
```

**Comment by joesonm** [comment]
> 

好了👌

**Comment by iGoogle-ink** [comment]
> > 
> 
> 好了👌

好的，那就是我的问题了，修改了一下，我发个 版本 吧
