### ISSUE TITLE
微信的提现接口和退款接口为什么没实现？

### ISSUE THREAD

**Issue by arden** [go-pay/gopay#207]
做为一个支付sdk，为什么微信的提现接口和退款接口为什么没实现？

**Comment by iGoogle-ink** [comment]
> 做为一个支付sdk，为什么微信的提现接口和退款接口为什么没实现？

没实现？不可能吧，是不是V3接口不支持，只能用V2的，如果V3有不太可能没实现，如果确实没实现，麻烦发个文档地址我去看看

**Comment by iGoogle-ink** [comment]
> 做为一个支付sdk，为什么微信的提现接口和退款接口为什么没实现？

退款有了，提现的话，会尽快补上，漏掉了

**Comment by arden** [comment]
// 退款（电商收付通）
	v3CommerceRefund      = "/v3/ecommerce/refunds/apply"
	v3CommerceRefundQuery = "/v3/ecommerce/refunds/id/%s"

**Comment by arden** [comment]
// 退款（电商收付通）
	v3CommerceRefund      = "/v3/ecommerce/refunds/apply"
	v3CommerceRefundQuery = "/v3/ecommerce/refunds/id/%s"

	// 提现
	v3Withdraw                = "/v3/ecommerce/fund/withdraw"                   // 特约商户余额提现 POST
	v3WithdrawStatusById      = "/v3/ecommerce/fund/withdraw/%s"                // withdraw_id 微信支付提现单号查询特约商户提现状态 GET
	v3WithdrawStatusByNo      = "/v3/ecommerce/fund/withdraw/out-request-no/%s" // withdraw_id 商户提现单号查询特约商户提现状态 GET
	v3WithdrawDownloadErrBill = "/v3/merchant/fund/withdraw/bill-type/%s"       // bill_type 按日下载提现异常文件 GET

这几个都还没实现，另外开通二级商户进件系统好像也是没有的，感觉现在看了很多这种微信相关的开源项目，基本上都是不全面的，总是感觉够用，得自己fork出来修改完善。

**Comment by iGoogle-ink** [comment]
> ```
> // 退款（电商收付通）
> v3CommerceRefund      = "/v3/ecommerce/refunds/apply"
> v3CommerceRefundQuery = "/v3/ecommerce/refunds/id/%s"
> 
> // 提现
> v3Withdraw                = "/v3/ecommerce/fund/withdraw"                   // 特约商户余额提现 POST
> v3WithdrawStatusById      = "/v3/ecommerce/fund/withdraw/%s"                // withdraw_id 微信支付提现单号查询特约商户提现状态 GET
> v3WithdrawStatusByNo      = "/v3/ecommerce/fund/withdraw/out-request-no/%s" // withdraw_id 商户提现单号查询特约商户提现状态 GET
> v3WithdrawDownloadErrBill = "/v3/merchant/fund/withdraw/bill-type/%s"       // bill_type 按日下载提现异常文件 GET
> ```
> 
> 这几个都还没实现，另外开通二级商户进件系统好像也是没有的，感觉现在看了很多这种微信相关的开源项目，基本上都是不全面的，总是感觉够用，得自己fork出来修改完善。

电商收付通的可能没做，提现的已经在 v1.5.67 里了
