### ISSUE TITLE
完结分账的接口没有实现吗？

### ISSUE THREAD

**Issue by fr4nkhe** [go-pay/gopay#211]
文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_4_5.shtml

**Comment by iGoogle-ink** [comment]
![image](https://user-images.githubusercontent.com/17245594/147476437-864d03ff-da60-480c-9b74-d7407548a171.png)
可能电商平台的，都没实现，后面补充吧

**Comment by iGoogle-ink** [comment]
@fr4nkhe  1.5.68，已补充

**Comment by fr4nkhe** [comment]
> @fr4nkhe 1.5.68，已补充

ok
