### ISSUE TITLE
alipay.ParseNotifyResult 目前被标注了Deprecated，后续会废弃吗

### ISSUE THREAD

**Issue by wiidz** [go-pay/gopay#213]
为何Deprecated，后续会有新的解析到结构体的函数吗？

**Comment by iGoogle-ink** [comment]
不推荐使用，因为 `NotifyRequest`  结构体是固定的，怕以后阿里云通知参数有改动，没办法解析.
所以推荐使用 `alipay.ParseNotifyToBodyMap()` 来解析到BodyMap中，再根据自己的需求，来取不同的参数，
也可以通过 `bm.JsonBody()` 解析出 json string，后续我会补充一个方法，直接支持将 BodyMap 中的内容解析到指定结构体。
