### ISSUE TITLE
服务商的查询退款接口缺了一个参数

### ISSUE THREAD

**Issue by fr4nkhe** [go-pay/gopay#214]
文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter4_1_10.shtml
和直联商户的接口比多了一个二级商户id

**Comment by iGoogle-ink** [comment]
@fr4nkhe 
感谢反馈，commit_id  d54d25a2 已处理

**Comment by fr4nkhe** [comment]
> @fr4nkhe 感谢反馈，commit_id [d54d25a](https://github.com/go-pay/gopay/commit/d54d25a2fa0ac30f12952d2460832f22994839cc) 已处理
v1.5.69的tag还没加，麻烦加一下，不然更新不了

**Comment by iGoogle-ink** [comment]
> > @fr4nkhe 感谢反馈，commit_id [d54d25a](https://github.com/go-pay/gopay/commit/d54d25a2fa0ac30f12952d2460832f22994839cc) 已处理
> > v1.5.69的tag还没加，麻烦加一下，不然更新不了

好的，如果实在着急，可以先按照  commit id 导入 mod 文件

**Comment by fr4nkhe** [comment]
> > > @fr4nkhe 感谢反馈，commit_id [d54d25a](https://github.com/go-pay/gopay/commit/d54d25a2fa0ac30f12952d2460832f22994839cc) 已处理
> > > v1.5.69的tag还没加，麻烦加一下，不然更新不了
> 
> 好的，如果实在着急，可以先按照 commit id 导入 mod 文件

好的
