### ISSUE TITLE
调用返回的错误疑惑

### ISSUE THREAD

**Issue by tarupo** [go-pay/gopay#221]
https://github.com/go-pay/gopay/blob/ecb483a34db0320f4798b61f4682ce94ae755e17/alipay/member_api.go#L30

这种写法在方法内部判断了支付宝那边的义务码, 非 “10000” 就返回一个```fmt.Errorf(..,)``` 是不是不太妥?

这样造成 可能的请求错误、可能的反序列化错误以及业务错误等混淆在一起的情况, 感觉比较奇怪?

**Comment by iGoogle-ink** [comment]
你感觉如何好呢？可以提一下你的建议，我参考学习一下

**Comment by tarupo** [comment]
> 你感觉如何好呢？可以提一下你的建议，我参考学习一下

对代码做了些修改 您可以查看下pr
