### ISSUE TITLE
alipay.user.certdoc.certverify.consult(实名证件信息比对验证咨询) 接口方法少了公共参数auth_token的传入

### ISSUE THREAD

**Issue by XianJiee** [go-pay/gopay#223]
alipay.user.certdoc.certverify.consult(实名证件信息比对验证咨询) 接口方法这里是不是少了公共参数auth_token的传入， 就算set进去也会在通用请求接口doAliPay中被过滤掉，没有像alipay.user.info.share(支付宝会员授权信息查询接口)接口一样作判别将auth_token写入

**Comment by iGoogle-ink** [comment]
好的，我确认一下，这个接口是否必须参数  auth_token

**Comment by iGoogle-ink** [comment]
1.5.71 版本，将修复这个问题，方法增加入参
