### ISSUE TITLE
微信的银行能力API有加入计划吗

### ISSUE THREAD

**Issue by shengdoushi** [go-pay/gopay#225]
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/Offline/apis/chapter11_2_1.shtml

有6个API:

- 获取对私银行卡号开启银行
- 查询支持个人业务的银行列表
- 查询支持对公业务的银行列表
- 查询省份列表
- 查询城市列表
- 查询支行列表

**Comment by iGoogle-ink** [comment]
@shengdoushi 好的，我看一下，会尽快补充上

**Comment by iGoogle-ink** [comment]
1.5.71 版本已添加，帮忙测试一下吧
