### ISSUE TITLE
服务商修改结算帐号接口参数错误

### ISSUE THREAD

**Issue by fr4nkhe** [go-pay/gopay#236]
位置：wechat/v3/applyment_for_sub.go
// 修改结算账号 API
//	Code = 0 is success
// 	服务商文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter11_1_3.shtml
// 	电商文档：https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_1_4.shtml

服务商该接口的请求方式应该是将sub_mchid放在url里，并去除post请求体里的sub_mchid字段

**Comment by iGoogle-ink** [comment]
好的，我看一下
