### ISSUE TITLE
微信支付实例化的时候，一直报错

### ISSUE THREAD

**Issue by ljx870923001** [go-pay/gopay#238]
![image](https://user-images.githubusercontent.com/9137060/160038448-7598a1ab-ce34-4fed-8cd6-f9fe3e2d2ce7.png)

**Comment by iGoogle-ink** [comment]
好的，我尽快看一下，感谢提供反馈

**Comment by ljx870923001** [comment]
好的，麻烦你了，这边停在了这一步，看你还需要我这边提供什么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-pay/gopay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-pay/gopay] 微信支付实例化的时候，一直报错 (Issue #238)





 
好的，我尽快看一下，感谢提供反馈

**Comment by iGoogle-ink** [comment]
能提供一下你使用的  gopay module 版本吗？ 我看看哪个版本的问题

**Comment by ljx870923001** [comment]
github.com/go-pay/gopay v1.5.74  这个版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-pay/gopay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-pay/gopay] 微信支付实例化的时候，一直报错 (Issue #238)





 
能提供一下你使用的  gopay module 版本吗？ 我看看哪个版本的问题

**Comment by iGoogle-ink** [comment]
我看了一下，你这是 使用了  DurationToUnit() 方法，是吧，能提供一下，当时传的参数 duration 值吗？我复现一下

**Comment by iGoogle-ink** [comment]
我大概也知道点什么了，我这边需要处理一下 int 的边界，应该换成 int64

**Comment by ljx870923001** [comment]
//构建微信支付客户端
func (t *booksOrderService) wechatPayClient(params model.BooksOrder, openid string) map[string]interface{} {
   MchId := common.WECHAT_MCHID
   SerialNo := common.WECHAT_SERIALNO
   APIv3Key := common.WECHAT_APIV3KEY
   //appid := common.WECHAT_APPID
   //notifyUrl := common.IMG_DOMAIN + common.WECHAT_NOTIFY_URL
   //total := params.PayPrice * 100

   //apiclient_key.pem
   /*dat, err := ioutil.ReadFile(os.Getenv("run_path") + "/config/apiclient_key.pem")
   if err != nil {
      panic("apiclient_key.pem文件读取失败")
   }*/

   _, _ = wechat.NewClientV3(MchId, SerialNo, APIv3Key, "")
   /*expire := time.Now().Add(30 * time.Minute).Format(time.RFC3339)
   bm := make(gopay.BodyMap)
   bm.Set("sp_appid", appid).
      Set("sp_mchid", MchId).
      Set("description", "购买书籍").
      Set("out_trade_no", params.Orderno).
      Set("time_expire", expire).
      Set("attach", "2").
      Set("notify_url", notifyUrl).
      SetBodyMap("amount", func(b gopay.BodyMap) {
         b.Set("total", total).
            Set("currency", "CNY")
      }).SetBodyMap("payer", func(b gopay.BodyMap) {
      b.Set("sp_openid", openid)
   })*/

   /*wxRsp, err := client.V3TransactionJsapi(context.TODO(), bm)
   if err != nil {
      kernel.Error("下单失败", err.Error())
      panic("下单失败")
   }
   if wxRsp.Code != 0 {
      panic("下单失败")
   }

   prepayid := wxRsp.Response.PrepayId
   payParam, err := client.PaySignOfApplet(appid, prepayid)
   if err != nil {
      kernel.Error("获取 JSAPI paySign失败", err.Error())
      panic("获取 JSAPI paySign")
   }

   resultMap := map[string]interface{}{
      "timeStamp": payParam.TimeStamp,
      "nonceStr":  payParam.NonceStr,
      "package":   payParam.Package,
      "signType":  payParam.SignType,
      "paySign":   payParam.PaySign,
   }*/

   return map[string]interface{}{}
}


代码我都注释了的，他还提示错误，就只剩下实例化了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-pay/gopay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-pay/gopay] 微信支付实例化的时候，一直报错 (Issue #238)





 
我看了一下，你这是 使用了  DurationToUnit() 方法，是吧，能提供一下，当时传的参数 duration 值吗？我复现一下

**Comment by iGoogle-ink** [comment]
我这边改成 int64，你根据 commit 导入再试一下，看看是否正常了

**Comment by ljx870923001** [comment]
我这边重新拉取包是吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-pay/gopay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-pay/gopay] 微信支付实例化的时候，一直报错 (Issue #238)





 
我这边改成 int64，你根据 commit 导入再试一下，看看是否正常了

**Comment by iGoogle-ink** [comment]
> 我这边重新拉取包是吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "go-pay/gopay" ***@***.***&gt;; 发送时间:&nbsp;2022年3月25日(星期五) 下午3:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [go-pay/gopay] 微信支付实例化的时候，一直报错 (Issue #238) 我这边改成 int64，你根据 commit 导入再试一下，看看是否正常了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

对，根据 commit id 拉取包的版本，因为我暂时还没发版

**Comment by iGoogle-ink** [comment]
我改好之后，可以直接把mod版本告诉你

**Comment by iGoogle-ink** [comment]
module 改成这个试试呢   `github.com/go-pay/gopay v1.5.75-0.20220325071055-3579a0bb4e34`

**Comment by ljx870923001** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月25日(星期五) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [go-pay/gopay] 微信支付实例化的时候，一直报错 (Issue #238)





 
module 改成这个试试呢   github.com/go-pay/gopay v1.5.75-0.20220325071055-3579a0bb4e34
 
&mdash;
