### ISSUE TITLE
V3Apply4SubModifySettlement 接口不应该判断bank_address_code 为必填

### ISSUE THREAD

**Issue by wzhsh90** [go-pay/gopay#243]
接口不应该判断bank_address_code 为必填

if err := bm.CheckEmptyError(
		"sub_mchid", "account_type", "account_bank", "bank_address_code", "account_number",
	); err != nil {
		return nil, err
	}

**Comment by iGoogle-ink** [comment]
@wzhsh90  好的，我去确认一下，可能文档有所改动
