### ISSUE TITLE
收付通过平台提现与平台提现预约状态接口没有

### ISSUE THREAD

**Issue by wzhsh90** [go-pay/gopay#244]
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_8_5.shtml
https://pay.weixin.qq.com/wiki/doc/apiv3_partner/apis/chapter7_8_6.shtml

**Comment by wzhsh90** [comment]
还有日终余额接口也没有

**Comment by iGoogle-ink** [comment]
好的，会补充的
