### ISSUE TITLE
V3EncryptText 加密bug

### ISSUE THREAD

**Issue by wzhsh90** [go-pay/gopay#245]
func (c *ClientV3) V3EncryptText(text string) (cipherText string, err error) {
	if c.wxPublicKey == nil || c.WxSerialNo == "" {
		return util.NULL, errors.New("WxPublicKey or WxSerialNo is null")
	}
	cipherByte, err := rsa.EncryptOAEP(sha1.New(), rand.Reader, c.wxPublicKey, []byte(text), nil)
	if err != nil {
		return "", fmt.Errorf("rsa.EncryptOAEP：%w", err)
	}
	return base64.StdEncoding.EncodeToString(cipherByte), nil
}
if c.wxPublicKey == nil || c.WxSerialNo == "" 这个来源AutoVerifySign 方法，如果不自动验签，则wxPublicKey 和WxSerialNo  为空

**Comment by wzhsh90** [comment]
wzhsh90 我的微信，有空可以加个微信，方便提供bug

**Comment by iGoogle-ink** [comment]
@wzhsh90  我的微信二维码就在Readme主页啊

**Comment by iGoogle-ink** [comment]
你可以使用  `client.SetPlatformCert()` 这个方法，单独设置证书等信息
![image](https://user-images.githubusercontent.com/17245594/162959828-634238bb-b725-4a3b-a737-6806f57d15e1.png)
