### ISSUE TITLE
支付宝部分接口更适合添加可传递公共参数

### ISSUE THREAD

**Issue by CyJaySong** [go-pay/gopay#252]
比如，创建支付订单的时候，开发者可能会有不同业务不同异步通知地址的需求。

**Comment by iGoogle-ink** [comment]
明白你的意思了，每次请求，可以支持自定义部分公共请求参数

**Comment by iGoogle-ink** [comment]
@CyJaySong  v1.5.79 版本已经支持了

**Comment by CyJaySong** [comment]
@iGoogle-ink Nice! 感谢！
