### ISSUE TITLE
paypal 缺少字段

### ISSUE THREAD

**Issue by robot-nan** [go-pay/gopay#253]
paypal OrderCapture接口   purchase_units-payments-captures 缺少很多字段， 比如id 是比较重要的， 需要用这个id 退款， 此id 和 response 的id 是不一样的。

**Comment by iGoogle-ink** [comment]
@robot-nan  好的，感谢提出，会尽快补充字段的

**Comment by iGoogle-ink** [comment]
我看了一下，字段都有，你检查一下你用的版本吧，另外，打开debug，希望能提供一下真实返回数据

**Comment by iGoogle-ink** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/17245594/172119534-64ada0e6-0f20-4adf-ac0f-91d168d04ca2.png">

**Comment by iGoogle-ink** [comment]
我看一直有，是不是返回数据就是空，导致拿不到？

**Comment by tangchangquan** [comment]
有群吗?我想询问下大佬们,怎么对接

**Comment by robot-nan** [comment]
ok 解决了
