### ISSUE TITLE
希望完善丰富下苹果支付的另外两个api

### ISSUE THREAD

**Issue by codingcn** [go-pay/gopay#272]
获取交易历史
https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history

获取订阅状态
https://developer.apple.com/documentation/appstoreserverapi/get_all_subscription_statuses

参考文章
https://www.purchasely.com/blog/the-new-app-store-api

**Comment by iGoogle-ink** [comment]
好的，抽空完善

**Comment by iGoogle-ink** [comment]
已增加，但未有条件测试
commit id ：a03285fb

**Comment by codingcn** [comment]
> 已增加，但未有条件测试 commit id ：a03285fb

大概看了下，这两个api都需要jwt签名才能成功调用，但commit好像没有看到相关代码

相关文档：https://developer.apple.com/documentation/appstoreserverapi/generating_tokens_for_api_requests

**Comment by iGoogle-ink** [comment]
> > 已增加，但未有条件测试 commit id ：a03285fb
> 
> 大概看了下，这两个api都需要jwt签名才能成功调用，但commit好像没有看到相关代码
> 
> 相关文档：https://developer.apple.com/documentation/appstoreserverapi/generating_tokens_for_api_requests

嗷嗷，调用对吧，调用我没有测试条件的，我没对接过apple的这块，要不你做一下处理，然后提交 PR 呗

**Comment by iGoogle-ink** [comment]
后续我研究一下吧，最近事多，心思在这上面少了

**Comment by codingcn** [comment]
@iGoogle-ink 已提交PR https://github.com/go-pay/gopay/pull/279
