### ISSUE TITLE
[支付宝] SetAppAuthToken 函数感觉位置不合理

### ISSUE THREAD

**Issue by CyJaySong** [go-pay/gopay#275]
根据[支付宝第三方应用授权规则](https://opendocs.alipay.com/isv/10467/xldcyq#%E6%8E%88%E6%9D%83%E8%A7%84%E5%88%99)
一个三方应用下可以绑定多个多个小程序，那么单纯在Client 设置一个AppAuthToken不太合理，client大多数开发场景应该是单例，一套系统中同时管理多个小程序时，这应该有问题

**Comment by CyJaySong** [comment]
仔细看了一下代码，alipay/client/client.go: 220行，调用的pubParamsHandle 是在从bm中取app_auth_token，但是213行中移除了，所以pubParamsHandle 始终拿不到用户放在bm的app_auth_token

**Comment by iGoogle-ink** [comment]
收到
