### ISSUE TITLE
支付宝异常处理问题

### ISSUE THREAD

**Issue by a314213** [go-pay/gopay#280]
func bizErrCheck(errRsp ErrorResponse) error {
	if errRsp.Code != "10000" {
		return &BizErr{
			Code:    errRsp.SubCode,
			Msg:     errRsp.Msg,
			SubCode: errRsp.SubCode,
			SubMsg:  errRsp.SubMsg,
		}
	}
	return nil
}
Code填充的是SubCode,直接返回Code是否更合理?

**Comment by iGoogle-ink** [comment]
> bizErrCheck

你说的对，这块应该是写错了，提交的PR看漏掉了，立马修复
