### ISSUE TITLE
支付宝授权返回请加上unionid，很重要哟

### ISSUE THREAD

**Issue by dannyzml** [go-pay/gopay#282]
type OauthTokenInfo struct {
	AccessToken  string `json:"access_token,omitempty"`
	AlipayUserId string `json:"alipay_user_id,omitempty"`
	ExpiresIn    int64  `json:"expires_in,omitempty"`
	ReExpiresIn  int64  `json:"re_expires_in,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	UserId       string `json:"user_id,omitempty"`
       // 加上
         UnionId       string `json:"union_id,omitempty"`
}

**Comment by iGoogle-ink** [comment]
好的，收到！

**Comment by iGoogle-ink** [comment]
expires_in  和 re_expires_in 是字符串类型的吗？我不记得了，但是看官网介绍，都是 string 类型的

**Comment by iGoogle-ink** [comment]
新 commit 已处理

**Comment by dannyzml** [comment]
nice !

**Comment by iGoogle-ink** [comment]
> nice !

下个版本会带上去，可以暂时先用 commit 使用
