### ISSUE TITLE
支付宝 SystemOauthToken 应支持三方调用

### ISSUE THREAD

**Issue by CyJaySong** [go-pay/gopay#285]
根据文档，[换取授权访问令牌](https://opendocs.alipay.com/apis/api_9/alipay.system.oauth.token) 是支持三方调用的，SystemOauthToken 需要增加一个传递 `app_auth_token `

**Comment by iGoogle-ink** [comment]
收到

**Comment by iGoogle-ink** [comment]
> 根据文档，[换取授权访问令牌](https://opendocs.alipay.com/apis/api_9/alipay.system.oauth.token) 是支持三方调用的，SystemOauthToken 需要增加一个传递 `app_auth_token `

v1.5.87 版本已处理该问题

**Comment by CyJaySong** [comment]
OauthTokenInfo 结构体，expires_in， re_expires_in 字段类型错误，应该为int64
