### ISSUE TITLE
支付宝签约支付 app 唤醒签约页面问题

### ISSUE THREAD

**Issue by seth-shi** [go-pay/gopay#294]
作者你好, 根据官方文档 app 进行签约应该是使用一个签名唤醒, 但是 SDK 已经去请求支付宝然后返回一个 HTML, 但是这个 HTML  app 是不能用的, 只能在 H5 页面使用.
app 调用签约应该是有点像这个 https://github.com/go-pay/gopay/pull/258

![image](https://user-images.githubusercontent.com/28035971/209778114-7bb2eab4-e719-4fc0-abac-0dd2827dcae4.png)

**Comment by iGoogle-ink** [comment]
你好，我有点没理解你的意思，这个接口能力我没接触过，等我有空再仔细看看，谢谢提出问题

**Comment by iGoogle-ink** [comment]
@seth-shi  你的意思是，需要返回相应的参数，让app端去进行签约，对吗？类似于 app支付，返回相应的支付参数嘛？

**Comment by seth-shi** [comment]
https://opendocs.alipay.com/open/041bxs

对，类似于 app 支付生成签名，我的建议提供一个方法，可以在服务端签名，现在貌似这个方法是私有的，

还可以提供一个同步支付扣款的功能，这个功能也常用，在连续包月周期扣款的时候

其实我代码也写得差不多了，或者提供一个分支

**Comment by seth-shi** [comment]
close by #295
