### ISSUE TITLE
支付宝免押相关接口是否有实现？

### ISSUE THREAD

**Issue by Rebellioncry** [go-pay/gopay#304]

**Comment by iGoogle-ink** [comment]
@Rebellioncry  应该是没有，支付宝文档多，分散杂，方便的话，可以发一下文档地址，后续增加进去，也可提交PR一起完善

**Comment by mackwan84** [comment]
> @Rebellioncry 应该是没有，支付宝文档多，分散杂，方便的话，可以发一下文档地址，后续增加进去，也可提交PR一起完善

https://opendocs.alipay.com/open/repo-0038jq?ref=api 支付宝预授权文档入口

**Comment by iGoogle-ink** [comment]
> > @Rebellioncry 应该是没有，支付宝文档多，分散杂，方便的话，可以发一下文档地址，后续增加进去，也可提交PR一起完善
> 
> https://opendocs.alipay.com/open/repo-0038jq?ref=api 支付宝预授权文档入口

收到
