### ISSUE TITLE
微信支付结算账号修改的接口有改动

### ISSUE THREAD

**Issue by fr4nkhe** [go-pay/gopay#316]
公告url：https://pay.weixin.qq.com/index.php/public/cms/content_detail?platformType=1&lang=zh&id=125582
提交的PR在#315

**Comment by iGoogle-ink** [comment]
> 公告url：https://pay.weixin.qq.com/index.php/public/cms/content_detail?platformType=1&lang=zh&id=125582 提交的PR在#315

好的，感谢
