### ISSUE TITLE
在微信服务商模式下，MicropayResponse少掉sub_openid，sub_is_subscribe 参数

### ISSUE THREAD

**Issue by liniu** [go-pay/gopay#317]
在微信服务商模式下，MicropayResponse少掉sub_openid，sub_is_subscribe 参数

**Comment by iGoogle-ink** [comment]
> 在微信服务商模式下，MicropayResponse少掉sub_openid，sub_is_subscribe 参数

好的，立马修复

**Comment by liniu** [comment]
谢谢
