### ISSUE TITLE
支付宝沙箱环境的网关地址有变动，请早点修改 ！！！

### ISSUE THREAD

**Issue by li-linfeng** [go-pay/gopay#318]
支付宝沙箱环境的网关是  https://openapi-sandbox.dl.alipaydev.com/gateway.do

现在库里的地址是：
sandboxBaseUrl     = "https://openapi.alipaydev.com/gateway.do"

希望能够调整

**Comment by iGoogle-ink** [comment]
@li-linfeng  能提供一下官方变动说明地址吗？我登录开发者平台发现，还是老的
![image](https://github.com/go-pay/gopay/assets/17245594/ff8aa437-ddab-40a1-81f2-fcbe52b5a056)

**Comment by iGoogle-ink** [comment]
看到了，新版沙箱环境确实是 改了，但是，新版老版通用吗？改成新版的沙箱地址，老版本的是否通用呢？

**Comment by nowgoo** [comment]
似乎支付宝关闭了新版沙箱，只有旧版可用了。
