### ISSUE TITLE
希望能支持自定义logger

### ISSUE THREAD

**Issue by iflamed** [go-pay/gopay#335]
现在logger 是包内部的，可以自定义logger的话，就可以和已有系统的logger 集成到一起了。

**Comment by iGoogle-ink** [comment]
> 现在logger 是包内部的，可以自定义logger的话，就可以和已有系统的logger 集成到一起了。

好的，后续改成interface

**Comment by kwooshung** [comment]
> 确实确实，这样我就毫不犹豫的选择这个库了。

**Comment by iGoogle-ink** [comment]
@iflamed @kwooshung 
我看已经支持了，你们自己分别实现一下应该就可以了
<img width="703" alt="image" src="https://github.com/go-pay/gopay/assets/17245594/5b77952c-c0e2-4d5a-b471-de95e34447d7">

**Comment by iflamed** [comment]
我关闭一下这个issue.
