### ISSUE TITLE
paypal 官方文档 相关字段显示已弃用

### ISSUE THREAD

**Issue by ShylockGao** [go-pay/gopay#336]
doc/paypal.md 
你好，paypal 介绍已过时，相关字段已弃用
![image](https://github.com/go-pay/gopay/assets/16751902/cd098eef-40e6-4ab1-9824-9b28efc3286d)

**Comment by iGoogle-ink** [comment]
> doc/paypal.md 你好，paypal 介绍已过时，相关字段已弃用 ![image](https://user-images.githubusercontent.com/16751902/260660140-cd098eef-40e6-4ab1-9824-9b28efc3286d.png)

OK
