### ISSUE TITLE
使用`UserAgreementPageSign`方法返回的`h5_url`不知道怎么使用

### ISSUE THREAD

**Issue by jhxxs** [go-pay/gopay#337]
返回的`h5_url`内容和官方提供的form提交方式不一样，不知道怎么操作了🥲

![image](https://github.com/go-pay/gopay/assets/7448223/10579bf8-b987-4a50-b501-ea2d055b3070)

![image](https://github.com/go-pay/gopay/assets/7448223/eadfc32e-a2b2-4015-97b7-6eee79654937)

**Comment by iGoogle-ink** [comment]
支付宝吗？这个我还真不太清楚

**Comment by iGoogle-ink** [comment]
支付宝吗？这个我还真不太清楚
