### ISSUE TITLE
支付宝批量转账接口还不能用吧 

### ISSUE THREAD

**Issue by zjm1126** [go-pay/gopay#355]
https://opendocs.alipay.com/apis/api_28/alipay.fund.batch.create 

测试了下 返回html乱码错误页面    有成功的吗。是不是需要申请。还是正在开放中

**Comment by zjm1126** [comment]
Set("total_count", 2).
		Set("trans_order_list", []gopay.BodyMap{
			gopay.BodyMap{
				"out_biz_no":   num2,
				"trans_amount": 700,
				"payee_info": map[string]any{
					"identity":      identity,
					"identity_type": "ALIPAY_LOGON_ID",
					"name":          name,
				},
			},
			gopay.BodyMap{
				"out_biz_no":   num3,
				"trans_amount": 48.78,
				"payee_info": map[string]any{
					"identity":      identity,
					"identity_type": "ALIPAY_LOGON_ID",
					"name":          name,
				},
			},

参数需要一个转账数组。 参数这么写没问题吧。

**Comment by iGoogle-ink** [comment]
> Set("total_count", 2). Set("trans_order_list", []gopay.BodyMap{ gopay.BodyMap{ "out_biz_no": num2, "trans_amount": 700, "payee_info": map[string]any{ "identity": identity, "identity_type": "ALIPAY_LOGON_ID", "name": name, }, }, gopay.BodyMap{ "out_biz_no": num3, "trans_amount": 48.78, "payee_info": map[string]any{ "identity": identity, "identity_type": "ALIPAY_LOGON_ID", "name": name, }, },
> 
> 参数需要一个转账数组。 参数这么写没问题吧。

数组写法好像不对哦，不是这么用的，你参考一下 `body_map_test.go` 文件内的 `TestBodyMapMarshalSlice` 方法吧
