### ISSUE TITLE
现在是否有计划考虑支持 stripe

### ISSUE THREAD

**Issue by SpenserCai** [go-pay/gopay#360]
现在官方出了sdk或许可以直接对接：https://github.com/stripe/stripe-go

**Comment by SpenserCai** [comment]
这是一个网络支付基础设施，支持135+的货币和支付方式，Midjourney，poe.com，ChatGPT，使用的支付都是这个，它在国外非常流行。

**Comment by iGoogle-ink** [comment]
> 这是一个网络支付基础设施，支持135+的货币和支付方式，Midjourney，poe.com，ChatGPT，使用的支付都是这个，它在国外非常流行。
> 
> https://stripe.com/

知道你的意思了，这是一个 聚合网络支付的 平台吧

**Comment by Jetereting** [comment]
> 这个确实有需求

@SpenserCai 2.9% + 30¢ 费率有点高吧

**Comment by zcyc** [comment]
> > 这个确实有需求
> 
> @SpenserCai 2.9% + 30¢ 费率有点高吧

确实高，也没有太多选择

**Comment by Jetereting** [comment]
> > > 这个确实有需求
> > 
> > 
> > @SpenserCai 2.9% + 30¢ 费率有点高吧
> 
> 确实高，也没有太多选择

美国公司怎么弄

**Comment by zcyc** [comment]
> > > > 这个确实有需求
> 
> > > 
> 
> > > 
> 
> > > @SpenserCai 2.9% + 30¢ 费率有点高吧
> 
> > 
> 
> > 确实高，也没有太多选择
> 
> 
> 
> 美国公司怎么弄

不清楚，公司不是我弄的

**Comment by Allen-Stephen-71** [comment]
这个我会  我对接过，目前运行的还行

**Comment by iGoogle-ink** [comment]
> 这个我会  我对接过，目前运行的还行

考虑提交PR接入吗？
