### ISSUE TITLE
苹果内购的TransactionInfo 加了价格字段 price currency

### ISSUE THREAD

**Issue by starhouse** [go-pay/gopay#362]
希望更新一下
TransactionInfo 结构体
https://developer.apple.com/documentation/appstoreservernotifications/jwstransactiondecodedpayload

**Comment by iGoogle-ink** [comment]
> 希望更新一下 TransactionInfo 结构体 https://developer.apple.com/documentation/appstoreservernotifications/jwstransactiondecodedpayload

好的，我看看

**Comment by iGoogle-ink** [comment]
> 好像漏了 apple/transaction_model.go文件的 TransactionsItem

补充过了，还不齐吗？
