### ISSUE TITLE
设置开启自动验签，是不是在回调接口就不用再次验证了？

### ISSUE THREAD

**Issue by ShylockGao** [go-pay/gopay#380]
RT
您好设置开启自动验签，
client.AutoVerifySign("")
是不是在回调接口就不用再次验证了？
alipay.VerifySignWithCert()

**Comment by iGoogle-ink** [comment]
@ShylockGao  一个是同步验签，同步验签可以不用了，但是异步回调验签还是需要

**Comment by ShylockGao** [comment]
好的谢谢啦
