### ISSUE TITLE
微信支付 v3，灰度证书会导致验签失败

### ISSUE THREAD

**Issue by cmzz** [go-pay/gopay#384]
SDK 的 `autoSgin` 使用 `GetAndSelectNewestCert()` 获取最新的一个证书来验证签名。通常这没什么问题。但是如果同时有多个生效的证书（比如新证书处于灰度中）时，响应可能并不是固定的某一个证书，那么就会导致验签失败。

要避免这个问题，就需要根据微信 response 的响应证书编号获取对应证书而非固定试用最新证书，说明文档：https://pay.weixin.qq.com/docs/merchant/development/interface-rules/privatekey-and-certificate.html

**Comment by iGoogle-ink** [comment]
我看现在就是用的response header里的SN对应的证书验签的
<img width="927" alt="image" src="https://github.com/go-pay/gopay/assets/17245594/34a1f0e6-d349-45ef-a706-107b2bdeb818">
