### ISSUE TITLE
微信付款码支付，返回结果中包含html字段判断错误

### ISSUE THREAD

**Issue by xiaoqiang-coder01** [go-pay/gopay#386]
微信付款码支付，返回判断，偶发性报错，代码位置：
![image](https://github.com/go-pay/gopay/assets/49513445/b2e861b2-771d-4157-84db-c87dc9c244f5)

微信付款码支付返回结果：
![image](https://github.com/go-pay/gopay/assets/49513445/334e8f3f-2ee6-4398-9b63-de32b208e7a0)

**Comment by xiaoqiang-coder01** [comment]
> 微信付款码支付，返回判断，偶发性报错，代码位置： ![image](https://private-user-images.githubusercontent.com/49513445/302168704-b2e861b2-771d-4157-84db-c87dc9c244f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDQ4NzgsIm5iZiI6MTcwNzEwNDU3OCwicGF0aCI6Ii80OTUxMzQ0NS8zMDIxNjg3MDQtYjJlODYxYjItNzcxZC00MTU3LTg0ZGItYzg3ZGM5YzI0NGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAzNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NDQwNTk3M2RmN2I4MDkyNmE1YjBkMTIyMzkwNTYwNmJjZjJmMGMyNGE2OGZkZDQ1OTBjMjlmMTNiMDRiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._tYzHYAYZfcCMO-sFe2UD21MU5egXV9cOVn--tZZYI0)
> 
> 微信付款码支付返回结果： ![image](https://private-user-images.githubusercontent.com/49513445/302168799-334e8f3f-2ee6-4398-9b63-de32b208e7a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDQ4NzgsIm5iZiI6MTcwNzEwNDU3OCwicGF0aCI6Ii80OTUxMzQ0NS8zMDIxNjg3OTktMzM0ZThmM2YtMmVlNi00Mzk4LTliNjMtZGUzMmIyMDhlN2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAzNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYmJmY2NkMGRlNDU5OTNmYWMyYzkzMGViMzQxNmVjOWQ0Mzk5OTNhYTUxYjQ1NTY1MjU4NTg4ZTYyNjc0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rDxJfuI2uo2gt5x8QWcrQEid_42U3fx0sSpq1fGQhSQ)

**Comment by xiaoqiang-coder01** [comment]
不好意思，新版本已解决了这个问题

**Comment by xiaoqiang-coder01** [comment]
新版本已修改，不好意思，请删除这个issue

**Comment by iGoogle-ink** [comment]
@xiaoqiang-coder01 同样感谢提出问题
