### ISSUE TITLE
apple.VerifyReceipt() => 苹果支付校验收据API 报21003

### ISSUE THREAD

**Issue by lscgzwd** [go-pay/gopay#388]
共享会话密钥是可选参数，没有的时候不能传，传空字符串会导致苹果返回21003

**Comment by iGoogle-ink** [comment]
@lscgzwd 可以说的详细点吗？

**Comment by lscgzwd** [comment]
apple/verify_model.go
中的结构体：VerifyRequest的Password和ExcludeOldTranscations两个属性在应用内购非订阅场景下是不需要的，不能传，哪怕传空字符串和false都不行，传了苹果接口会报错，返回21003。所以在最后json序列化成字符串传给苹果时，需要做判断的，空的时候不要传。
