### ISSUE TITLE
2024/04/09 13:53:47.730283 notification_v2_test.go:24: [ERROR] >> x509: certificate has expired or is not yet valid: current time 2024-04-09T13:53:47+08:00 is after 2023-09-24T02:50:33Z

### ISSUE THREAD

**Issue by hujiahuan** [go-pay/gopay#389]
2024/04/09 13:53:47.730283 notification_v2_test.go:24: [ERROR] >> x509: certificate has expired or is not yet valid: current time 2024-04-09T13:53:47+08:00 is after 2023-09-24T02:50:33Z

请问,这个错误怎么处理?

**Comment by iGoogle-ink** [comment]
看样子是证书到期了？

**Comment by hujiahuan** [comment]
嗯,我看好像是写死在代码里的.

**Comment by iGoogle-ink** [comment]
> 嗯,我看好像是写死在代码里的.

实在不好意思，Apple 支付这块是别人提交的，我本人没有测试条件，如果有问题，还请一起找出问题完善。

**Comment by hujiahuan** [comment]
没事没事,太客气了.已经很好了,持续支持.希望gopay越来越好.


苯猪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-pay/gopay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月13日(星期六) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-pay/gopay] 2024/04/09 13:53:47.730283 notification_v2_test.go:24: [ERROR] &gt;&gt; x509: certificate has expired or is not yet valid: current time 2024-04-09T13:53:47+08:00 is after 2023-09-24T02:50:33Z (Issue #389)





  
嗯,我看好像是写死在代码里的.
  
实在不好意思，Apple 支付这块是别人提交的，我本人没有测试条件，如果有问题，还请一起找出问题完善。
