### ISSUE TITLE
微信支付V2统一下单404

### ISSUE THREAD

**Issue by Boreals** [go-pay/gopay#396]
https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder
打断点发现WECHAT.UnifiedOrder(bm)在非正式环境中，会调以上接口，出现了404

**Comment by iGoogle-ink** [comment]
> https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder 打断点发现WECHAT.UnifiedOrder(bm)在非正式环境中，会调以上接口，出现了404

莫不是已经不支持 沙箱环境了？这块还真不清楚，v2应该是被腾讯淘汰的，推荐改用 微信v3接口
