### ISSUE TITLE
v1.5.101 V3Refund 报异常

### ISSUE THREAD

**Issue by liniu** [go-pay/gopay#398]
v1.5.101 V3Refund 报异常 ，信息如下

`
 json: cannot unmarshal array into Go struct field RefundOrderAmount.amount.from of type wechat.From, bytes: {"amount":{"currency":"CNY","discount_refund":0,"from":[],"payer_refund":200,"payer_total":200,"refund":200,"refund_fee":1,"settlement_refund":200,"settlement_total":200,"total":200},"channel":"ORIGINAL","create_time":"2024-06-11T10:16:44+08:00","funds_account":"AVAILABLE","out_refund_no":"36769388899602434","out_trade_no":"36769388899602433","promotion_detail":[],"refund_id":"50310010152024061103641176773","status":"PROCESSING","transaction_id":"4200002311202406113875557670","user_received_account":"建设银行借记卡5275"}
`

**Comment by liniu** [comment]
看了源码，"from":[]  是数组，而代码里面是*Form 对象。

**Comment by iGoogle-ink** [comment]
> 看了源码，"from":[] 是数组，而代码里面是*Form 对象。

感谢提出问题，我处理一下
