### ISSUE TITLE
BUG: cannot unmarshal array into Go struct field RefundOrderAmount.amount.from of type wechat.From

### ISSUE THREAD

**Issue by lswwyp** [go-pay/gopay#399]
调用V3Refund方法退款报错，实际上退款成功了：
{"error": "[unmarshal error]: json: cannot unmarshal array into Go struct field RefundOrderAmount.amount.from of type wechat.From, bytes: {\"amount\":{\"currency\":\"CNY\",\"discount_refund\":0,\"from\":[],\"payer_refund\":1,\"payer_total\":600,\"refund\":1,\"refund_fee\":0,\"settlement_refund\":1,\"settlement_total\":600,\"total\":600},\"channel\":\"ORIGINAL\",\"create_time\":\"2024-06-17T13:55:37+08:00\",\"funds_account\":\"AVAILABLE\",\"out_refund_no\":\"refund_16\",\"out_trade_no\":\"c28b6b1c6186462b8ce8e50c5907915e\",\"promotion_detail\":[],\"refund_id\":\"5030091232024061719734893787\",\"status\":\"PROCESSING\",\"transaction_id\":\"4200002322202406112347972073\",\"user_received_account\":\"支付用户零钱\"}"}

**Comment by iGoogle-ink** [comment]
> 调用V3Refund方法退款报错，实际上退款成功了： {"error": "[unmarshal error]: json: cannot unmarshal array into Go struct field RefundOrderAmount.amount.from of type wechat.From, bytes: {"amount":{"currency":"CNY","discount_refund":0,"from":[],"payer_refund":1,"payer_total":600,"refund":1,"refund_fee":0,"settlement_refund":1,"settlement_total":600,"total":600},"channel":"ORIGINAL","create_time":"2024-06-17T13:55:37+08:00","funds_account":"AVAILABLE","out_refund_no":"refund_16","out_trade_no":"c28b6b1c6186462b8ce8e50c5907915e","promotion_detail":[],"refund_id":"5030091232024061719734893787","status":"PROCESSING","transaction_id":"4200002322202406112347972073","user_received_account":"支付用户零钱"}"}

最新的 commit 已经修复，我这边尽快打个Release 吧

**Comment by iGoogle-ink** [comment]
v1.5.102 版本已经修复此数据解析失败问题
