### ISSUE TITLE
支持 alipay.pay.app.marketing.consult (商户前置内容咨询接口) 有接入计划吗

### ISSUE THREAD

**Issue by Zalintyle** [go-pay/gopay#400]
https://opendocs.alipay.com/pre-open/296d225f_alipay.pay.app.marketing.consult?scene=9f4588ab7b324d10aa1e4fb9e4363961&pathHash=971aad82

**Comment by iGoogle-ink** [comment]
> https://opendocs.alipay.com/pre-open/296d225f_alipay.pay.app.marketing.consult?scene=9f4588ab7b324d10aa1e4fb9e4363961&pathHash=971aad82

好的，我尽快补充一下

**Comment by iGoogle-ink** [comment]
最新的 commit id 里已经有补充了，可以先用 commit id测试一下看看
<img width="804" alt="image" src="https://github.com/go-pay/gopay/assets/17245594/556a6a63-d82f-4e11-80ba-22a53509a090">
