### ISSUE TITLE
[xlog] 日志输出到文件

### ISSUE THREAD

**Issue by Alice52** [go-pay/gopay#401]
```go
if c.DebugSwitch == gopay.DebugOn {
      xlog.Debugf("Wechat_V3_Url: %s", url)
      xlog.Debugf("Wechat_V3_Req_Body: %s", bm.JsonBody())
      xlog.Debugf("Wechat_V3_Req_Headers: %#v", req.Header)
}
```

以上源码中的 Debug 日志怎么重定向到指定文件， 比如go-zero的日志文件 @iGoogle-ink

**Comment by iGoogle-ink** [comment]
> ```go
> if c.DebugSwitch == gopay.DebugOn {
>       xlog.Debugf("Wechat_V3_Url: %s", url)
>       xlog.Debugf("Wechat_V3_Req_Body: %s", bm.JsonBody())
>       xlog.Debugf("Wechat_V3_Req_Headers: %#v", req.Header)
> }
> ```
> 
> 以上源码中的 Debug 日志怎么重定向到指定文件， 比如go-zero的日志文件 @iGoogle-ink

目前不支持输出到指定文件以及类型，调试日志默认输出到 stdout。
而且开发调试完成后，并不建议在线上环境输出这些信息。
