### ISSUE TITLE
这个包能恢复一下吗 ？以前的项目在使用呢

### ISSUE THREAD

**Issue by crisis111** [go-pay/gopay#404]
https://github.com/iGoogle-ink/gotil/' not found    version  1.7.0

**Comment by iGoogle-ink** [comment]
> https://github.com/iGoogle-ink/gotil/

我已经还原了，但是版本是 v0.0.1，你去试试吧

**Comment by crisis111** [comment]
试了一下不行啊 ，我没有说清楚，我引入的是 i!google-ink\gopay@v1.5.19  ，这个sdk版本里面引入了 require github.com/iGoogle-ink/gotil v1.0.7，  现在gotil@v1.0.7拉不到了 ，麻烦你能还原一下吗 ？
