### ISSUE TITLE
麻烦你恢复一下 gotil@v1.0.7  

### ISSUE THREAD

**Issue by crisis111** [go-pay/gopay#408]
我试了一下gotil@v0.0.1不行啊 ，上次我没有说清楚，我引入的是 i!google-ink\gopay@v1.5.19 ，这个sdk版本里面引入了 require github.com/iGoogle-ink/gotil v1.0.7， 现在gotil@v1.0.7拉不到了 ，麻烦你能还原一下吗 ？

**Comment by iGoogle-ink** [comment]
> 我试了一下gotil@v0.0.1不行啊 ，上次我没有说清楚，我引入的是 i!google-ink\gopay@v1.5.19 ，这个sdk版本里面引入了 require github.com/iGoogle-ink/gotil v1.0.7， 现在gotil@v1.0.7拉不到了 ，麻烦你能还原一下吗 ？

不考虑升级吗？那我去打个 v1.0.7 的tag吧，推荐你升级一下 gopay 了
