### ISSUE TITLE
paypal  OrderCapture 接口404

### ISSUE THREAD

**Issue by kingparks** [go-pay/gopay#409]
{404 {"name":"RESOURCE_NOT_FOUND","details":[{"issue":"INVALID_RESOURCE_ID","description":"Specified resource ID does not exist. Please check the resource ID and try again."}],"message":"The specified resource does not exist.","debug_id":"0e66ef35b0d61","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID","rel":"information_link","method":"GET"}]} 0x14000392600 0x140003485a0}

**Comment by kingparks** [comment]
2024/07/30 16:26:38.586643 request.go:44: [DEBUG] >> PayPal_Url: https://api-m.paypal.com/v2/checkout/orders/xxxxxxxxx/capture
2024/07/30 16:26:38.586648 request.go:45: [DEBUG] >> PayPal_Req_Body: null
2024/07/30 16:26:38.586657 request.go:46: [DEBUG] >> PayPal_Req_Headers: http.Header{"Accept":[]string{"*/*"}, "Authorization":[]string{"Bearer A21AANHELTVoBxvrrN4JV0HKB7LDn1kkb9PU9Y33dTMY1u1Cjczkt62QOE6ueurIn86afMJHpXb8pD0DBkpKk3Y_s6-f6jIeQ"}, "Content-Type":[]string{"application/json"}}
2024/07/30 16:26:39.026282 request.go:53: [DEBUG] >> PayPal_Response: 404 > {"name":"RESOURCE_NOT_FOUND","details":[{"issue":"INVALID_RESOURCE_ID","description":"Specified resource ID does not exist. Please check the resource ID and try again."}],"message":"The specified resource does not exist.","debug_id":"35fdff7f0c64e","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_RESOURCE_ID","rel":"information_link","method":"GET"}]}

**Comment by Allen-Stephen-71** [comment]
这个是正常的，你需要考虑这个情况，超时取消
