### ISSUE TITLE
运行报错: predeclared any requires go1.18 or later

### ISSUE THREAD

**Issue by yxw2014** [go-pay/gopay#410]
`ye@weis-MBP tt % go run notify.go
 # github.com/go-pay/gopay/pkg/jwt
../../pkg/mod/github.com/go-pay/gopay@v1.5.103/pkg/jwt/rsa_pss.go:85:75: predeclared any requires go1.18 or later (file declares //go:build go1.4)
../../pkg/mod/github.com/go-pay/gopay@v1.5.103/pkg/jwt/rsa_pss.go:119:62: predeclared any requires go1.18 or later (file declares //go:build go1.4)`

报错无法运行

**Comment by yxw2014** [comment]
v1.5.103 这个tag有上面的问题，其他tag没问题，我是调用了GetNotificationHistory方法。我当前go版本
go version go1.22.5 darwin/arm64

**Comment by yxw2014** [comment]
还有个问题： https://github.com/go-pay/gopay/blob/main/pkg/jwt/rsa.go#L77 
这个文件里面又import了github.com/go-pay/gopay包， 为什么不使用相对路径呢？
就是说你把gopay.VerifySignatureErr 这种东西放到一个单独的包下面，这样更清晰，更好吧？😅

**Comment by wxyz520** [comment]
predeclared any requires go1.18 or later (-lang was set to go1.21; check go.mod)

**Comment by wxyz520** [comment]
predeclared any requires go1.18 or later (-lang was set to go1.21; check go.mod)  同样遇到了这个问题...

**Comment by iGoogle-ink** [comment]
好的，我紧急处理一下

**Comment by yxw2014** [comment]
v1.5.104 我刚测试了， 是好的！
