### ISSUE TITLE
微信商家批次转账到零钱回调通知

### ISSUE THREAD

**Issue by wuqinqiang** [go-pay/gopay#411]
是不是少了微信商家批次转账到零钱回调的解析，没有在notify找到。
https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch-callback-notice.html

**Comment by iGoogle-ink** [comment]
> 是不是少了微信商家批次转账到零钱回调的解析，没有在notify找到。 https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch-callback-notice.html

我看一下，补充上

**Comment by wuqinqiang** [comment]
感谢
