### ISSUE TITLE
Apple付费 LookUpOrderId和GetAllSubscriptionStatuses两个调用返回的Transaction结构不同

### ISSUE THREAD

**Issue by yxw2014** [go-pay/gopay#426]
GetAllSubscriptionStatuses返回的是：
// TransactionInfo https://developer.apple.com/documentation/appstoreservernotifications/jwstransactiondecodedpayload
type TransactionInfo struct {

LookUpOrderId返回的是
// Doc: https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload
type TransactionsItem struct {

实际上这两个调用都是调用server api，返回的应该是同一个结构，和appstoreserverapi/jwstransactiondecodedpayload保持一致才对，不明白这里为什么不同？最好统一下， 更规范，更合理！

**Comment by iGoogle-ink** [comment]
好的

**Comment by iGoogle-ink** [comment]
@yxw2014  如果你有想法可以改一下，提交PR。
我只是根据文档写，并没有实际用过apple 支付相关的东西，所以没有做统一
