### ISSUE TITLE
微信支付：新申请的微信支付商户号出现「证书不存在」的报错，因为新申请的商户号需要使用公钥模式，能兼容下公钥模式吗

### ISSUE THREAD

**Issue by Axinyu** [go-pay/gopay#428]
### 1. 问题说明
新申请的微信支付商户号出现「证书不存在」的报错，因为新申请的商户号需要使用公钥模式，自动验签等不再支持平台证书；

### 3. 关于新商户调用接口验签方式变更通知
https://developers.weixin.qq.com/community/pay/doc/0002c6a7cf438818df52145b863c01

### 4. 相关代码截图
![image](https://github.com/user-attachments/assets/718f9635-0ed8-4183-85d5-8b1cde9a74a8)
![image](https://github.com/user-attachments/assets/53498d58-7fe9-4036-a3b5-41bfcca57742)

### 5. 报错信息
`client.AutoVerifySign()`方法自动验签会提示:
```json
{
"code":"RESOURCE_NOT_EXISTS",
"message":"无可用的平台证书，请在商户平台-API安全申请使用微信支付公钥。可查看指引https://pay.weixin.qq.com/docs/merchant/products/platform-certificate/wxp-pub-key-guide.html"
}
```

**Comment by cattle2002** [comment]
我也是遇到了这个问题 官方的库真是一言难尽

**Comment by iGoogle-ink** [comment]
@Axinyu @cattle2002  好的，但是我最近忙，需要时间研究，或者你们严研究好了提交个PR。

**Comment by iGoogle-ink** [comment]
@Axinyu  能帮忙看看这个 PR 是否可以解决问题吗？#430

**Comment by Axinyu** [comment]
> @Axinyu 能帮忙看看这个 PR 是否可以解决问题吗？#430

没问题，自签成功
![image](https://github.com/user-attachments/assets/fade4fdb-6eaa-4840-8959-8b368d7845ab)

**Comment by Axinyu** [comment]
> @Axinyu 能帮忙看看这个 PR 是否可以解决问题吗？#430

没问题，自签成功
![image](https://github.com/user-attachments/assets/e0c6a6df-a12b-478f-a364-a460b802b36a)

**Comment by Axinyu** [comment]
> @Axinyu 能帮忙看看这个 PR 是否可以解决问题吗？#430

然后需要加个error返回

**Comment by iGoogle-ink** [comment]
> > @Axinyu 能帮忙看看这个 PR 是否可以解决问题吗？#430
> 
> 然后需要加个error返回

好的，我补充一下

**Comment by Axinyu** [comment]
自签成功，没有问题
![image](https://github.com/user-attachments/assets/81bb1e0b-e958-4041-9c99-8aff9e49b150)

**Comment by equinox-sun** [comment]
> > > @Axinyu 能帮忙看看这个 PR 是否可以解决问题吗？#430
> > 
> > 
> > 然后需要加个error返回
> 
> 好的，我补充一下，PR已经合并，你可以使用最新的 commit id 拉取测试一下，谢谢

我现在用的go版本是go1.21，如果用最新commit id则版本有问题，请问应该怎么办呢？
