### ISSUE TITLE
关于支付宝签名方式的问题

### ISSUE THREAD

**Issue by lorenwe** [go-pay/gopay#44]
支付宝一些接口还支持MD5的签名方式，后续版本会集成进来吗？

**Comment by iGoogle-ink** [comment]
@lorenwe 
方便发出相关地址链接或者案例参考吗？我这边不是很清楚

**Comment by lorenwe** [comment]
支付宝有个提交数据后跳转到支付宝收银台的方式，就是将所有数据通过get方式提交到https://mapi.alipay.com/gateway.do这个地址，参数都是跟在这个地址后面的，其中的签名方式就是通过MD5来签名的，提交到这个地址后如果成功就会重定向到支付宝网页收银台，然后支付就行了

**Comment by lorenwe** [comment]
参考文档 https://opendocs.alipay.com/open/58/103591

**Comment by mgr9525** [comment]
即时到账的吧，https://github.com/mgr9525/gopay
下单：
![image](https://user-images.githubusercontent.com/9899755/86134430-30c64500-bb1c-11ea-8cd1-5d76f980dc77.png)
回调：
![image](https://user-images.githubusercontent.com/9899755/86134485-4471ab80-bb1c-11ea-8b5a-ee029ccffb83.png)
