### ISSUE TITLE
希望增加服务商模式

### ISSUE THREAD

**Issue by sun757253857** [go-pay/gopay#66]
希望增加服务商模式，谢谢

**Comment by iGoogle-ink** [comment]
@sun757253857 
好的，微信是吧？可以的一起处理，提PR
我后续有时间也会添加的

**Comment by sun757253857** [comment]
我测试了一下，下单和退款都是可以直接用的，地址相同的，多了几个参数而已。
有问题的就是交易结果通知的验签，NotifyRequest结构体需要加一下几个参数就好了

**Comment by stelin** [comment]
服务商模式也是刚需，我也遇到了，不知道什么时候支持

**Comment by sun757253857** [comment]
> 服务商模式也是刚需，我也遇到了，不知道什么时候支持

 可以直接用的，多了几个参数就行，结果通知用ParseNotifyToBodyMap处理

**Comment by stelin** [comment]
嗯，我试试

**Comment by iGoogle-ink** [comment]
good

**Comment by Evangelione** [comment]
> > 服务商模式也是刚需，我也遇到了，不知道什么时候支持
> 
> 可以直接用的，多了几个参数就行，结果通知用ParseNotifyToBodyMap处理

可以提供一下代码吗，服务商的支付地址不一样，怎么直接用呢？

**Comment by Evangelione** [comment]
我用的v3版本

**Comment by sun757253857** [comment]
> 我用的v3版本

我之前用的v2版本,没试过v3,换个地址应该也可以吧,就差了几个参数

**Comment by Evangelione** [comment]
@iGoogle-ink v3服务商支付的回调结果不一样，payer的结构体不同，希望能完善一下 谢谢 ^_^
