### ISSUE TITLE
请教一个问题：微信支付，我如果只初始化一个全局Client实例，在处理不同请求的时候会不会有并发瓶颈？（比如同时有1000人下单，会不会有阻塞的情况）

### ISSUE THREAD

**Issue by zhangbo0724** [go-pay/gopay#70]

**Comment by llgoer** [comment]
客户端请求的时候是带锁的，一个处理完处理另外一个，同时下单会阻塞

**Comment by zhangbo0724** [comment]
真实应用场景的时候肯定会有并发的需求，如果是同步执行的话就弱化了SDK的功能。只所以只实例化一个Client实例，是为了针对需要证书的请求时，避免频繁加载证书，但是单实例又会遇到并发的问题。希望后续可以完善SDK，考虑并发的场景。谢谢！

**Comment by llgoer** [comment]
没必要担心这个问题，一次请求本身就挺快的了，1000人同时支付，你这业务量真大

**Comment by iGoogle-ink** [comment]
@zhangbo0724 
客户端请求的锁是 读写锁，而且只加的读锁，以防在读的时候被改掉，读锁的性能很高的，这点暂时还不用担心

**Comment by fwhezfwhez** [comment]
为啥要加锁，看不明白。
只有存在竞态的业务，才需要锁。

支付的sdk，很显然，所有业务都不是竞态的。

代码的架构上，还是有一点问题的
