### ISSUE TITLE
在alipay.SystemOauthToken 换取授权访问令牌那发现几个问题

### ISSUE THREAD

**Issue by 1755616537** [go-pay/gopay#87]
在SystemOauthToken 换取授权访问令牌那发现几个问题。选择的加签模式是公钥证书模式，没加app_cert_sn和alipay_root_cert_sn字段通不过验签.最后return没返回值报错.报错不提示rsp.ErrorResponse.SubMsg里面的报错信息问题.没判断是否请求成功就返回rsp

**Comment by iGoogle-ink** [comment]
嗯，client 方法里的 SystemOauthToken 是做过判断的，公共方法里的，没处理这块，用户自己处理吧
